### ISSUE TITLE
Adapting code to my case

### ISSUE THREAD

**Issue by kadiraltug** [cbaezp/roulette#4]
I want to work with my dataset and then train it and predict the result. How can I do this? Is there any progress about it? I added example video . Can you give me suggestion ? Have a nice day sir.

![utils_output](https://github.com/cbaezp/roulette/assets/57407135/2b1ba74a-161a-4dd7-891e-fc93c04960c4)

**Comment by cbaezp** [comment]
> I want to work with my dataset and then train it and predict the result. How can I do this? Is there any progress about it? I added example video . Can you give me suggestion ? Have a nice day sir.
> 
> ![utils_output](https://private-user-images.githubusercontent.com/57407135/335886147-2b1ba74a-161a-4dd7-891e-fc93c04960c4.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczNjU2OTUsIm5iZiI6MTcxNzM2NTM5NSwicGF0aCI6Ii81NzQwNzEzNS8zMzU4ODYxNDctMmIxYmE3NGEtMTYxYS00ZGQ3LTg5MWUtZmM5M2MwNDk2MGM0LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAyVDIxNTYzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyYjEwODQ2MDg4NTFlZjhlZDZlMWU0YzZjYzkxNzUwNjM1YTU5N2VhZjQ2NjRiNjJjOWZiYjc3Mjg0ZDQ3Y2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.84Yg9vhkLjqNqJrprQnyuP4GTZlWO2boQxIG_J_b3yo) [ ![utils_output](https://private-user-images.githubusercontent.com/57407135/335886147-2b1ba74a-161a-4dd7-891e-fc93c04960c4.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczNjU2OTUsIm5iZiI6MTcxNzM2NTM5NSwicGF0aCI6Ii81NzQwNzEzNS8zMzU4ODYxNDctMmIxYmE3NGEtMTYxYS00ZGQ3LTg5MWUtZmM5M2MwNDk2MGM0LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAyVDIxNTYzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyYjEwODQ2MDg4NTFlZjhlZDZlMWU0YzZjYzkxNzUwNjM1YTU5N2VhZjQ2NjRiNjJjOWZiYjc3Mjg0ZDQ3Y2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.84Yg9vhkLjqNqJrprQnyuP4GTZlWO2boQxIG_J_b3yo) ](https://private-user-images.githubusercontent.com/57407135/335886147-2b1ba74a-161a-4dd7-891e-fc93c04960c4.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczNjU2OTUsIm5iZiI6MTcxNzM2NTM5NSwicGF0aCI6Ii81NzQwNzEzNS8zMzU4ODYxNDctMmIxYmE3NGEtMTYxYS00ZGQ3LTg5MWUtZmM5M2MwNDk2MGM0LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAyVDIxNTYzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyYjEwODQ2MDg4NTFlZjhlZDZlMWU0YzZjYzkxNzUwNjM1YTU5N2VhZjQ2NjRiNjJjOWZiYjc3Mjg0ZDQ3Y2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.84Yg9vhkLjqNqJrprQnyuP4GTZlWO2boQxIG_J_b3yo) [ ](https://private-user-images.githubusercontent.com/57407135/335886147-2b1ba74a-161a-4dd7-891e-fc93c04960c4.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczNjU2OTUsIm5iZiI6MTcxNzM2NTM5NSwicGF0aCI6Ii81NzQwNzEzNS8zMzU4ODYxNDctMmIxYmE3NGEtMTYxYS00ZGQ3LTg5MWUtZmM5M2MwNDk2MGM0LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAyVDIxNTYzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyYjEwODQ2MDg4NTFlZjhlZDZlMWU0YzZjYzkxNzUwNjM1YTU5N2VhZjQ2NjRiNjJjOWZiYjc3Mjg0ZDQ3Y2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.84Yg9vhkLjqNqJrprQnyuP4GTZlWO2boQxIG_J_b3yo)

I suggest following a process similar to the one demonstrated in my video. Ideally, you should use a high-angle or aerial shot to visualize the entire scene as a matrix with x and y coordinates, especially if you plan to rely solely on computer vision without additional sensors. You will also need to establish a fixed point in your canvas coordinates to calculate the speed of the ball and the spinning roulette based on this fixed point.

For ball detection, you can train a model to recognize the specific object and plot its position in each frame. This will eventually give you the trajectory, i.e., if you have a 60fps video, you should have 60 different x,y coordinates for the ball for each second of your video. The same principle applies to the roulette itself. The easiest way to achieve this is by using the green slot, which can be detected using plain OpenCV without the need to train a model.

It's also possible to use OpenCV to detect the ball itself based on its shape and color without training a model. However, the efficiency of this technique may depend on the fps of your video.

Once you have pinpointed all the positions, you should be able to derive speed, trajectory, and potentially predict the landing zone. Of course, there are other variables you need to account for. This is just a general summary of my approach.

**Comment by kadiraltug** [comment]
Thanks for reply sir. Have you tried to continue developing the project later? Btw, I am recording the video from an online site. Because of this, it is very difficult to find video taken from an overhead camera.

**Comment by kadiraltug** [comment]
Hello sir, I calculated angular speed of the ball and whell. But I didnt predict real result. What is the problem? Do you have any idea?

**Comment by cbaezp** [comment]
> Hello sir, I calculated angular speed of the ball and whell. But I didnt predict real result. What is the problem? Do you have any idea?

There could me a number of variables specific to your video and dataset. I'm not sure exactly what the problem could be.
